### ISSUE TITLE
 Inconsistent Behavior with DataWriterQos "HistoryQosPolicyKind::KeepLast" in a Publisher-Subscriber Scenario

### ISSUE THREAD

**Issue by ari-github** [s2e-systems/dust-dds#167]
I have encountered a puzzling issue while working with a data writer configured with a specific Quality of Service (QoS) policy. 
Here's my QoS configuration:

```rust
let writer_qos = DataWriterQos {
    reliability: ReliabilityQosPolicy {
        kind: ReliabilityQosPolicyKind::Reliable,
        max_blocking_time: DurationKind::Finite(Duration::new(1, 0)),
    },
    durability: DurabilityQosPolicy {
        kind: DurabilityQosPolicyKind::TransientLocal,
    },
    history: HistoryQosPolicy {
        kind: HistoryQosPolicyKind::KeepLast(1),
    },
    ..Default::default()
};
```
My setup involves a data writer that writes data 10 times, and then a data reader is initiated with the same QoS settings. Surprisingly, I observe the following behavior:

When the `HistoryQosPolicyKind` is set to` KeepLast(1)`, I receive the first and the last message.
If I modify the `HistoryQosPolicy` to `KeepLast(2)`, I receive the first, the second, and the last messages.

I expected to only receive the last message when the HistoryQosPolicyKind is set to KeepLast(1). Why am I receiving both the first and last messages in this case?
Furthermore, when I set the `HistoryQosPolicyKind` to `KeepLast(2)`, I anticipate receiving only the last two messages, not the first, second, and last messages. Is this behavior in line with the expected outcome?

Additional Context:
I'm using the `hello_world_publisher` with the same message ID for all the messages, only changing the message content during each write operation.

**Comment by jrebelo** [comment]
Dear @ari-github, thank you for reporting this issue and the detailed description. Your understanding is correct and the behavior should indeed be that the last sample is received when having a `KeepLast(1)` for `HistoryQosPolicy`. We have fixed this bug on the associated PR #168
