### ISSUE TITLE
Option Serialization Support

### ISSUE THREAD

**Issue by ari-github** [s2e-systems/dust-dds#171]
I'm inquiring about the possibility of adding serialization support for Option types?
Are there any existing mechanisms for working with Option types in DDS messages as of now?

**Comment by jrebelo** [comment]
Hi @ari-github, there are some ways to handle this but the answer depends a little on your exact use case. Could you give a little more detail on what you try to achieve when sending the Option?

**Comment by jrebelo** [comment]
In a case like this my advice for simplicity would be to remove the Option. You can use the empty String to represent the scenario where there is nothing. This would allow you to use all the standard mechanisms to send and access the data. If you have this struct `struct Person {
    id: i32,
    name: String,
}` it will be serialized on the wire with 4 bytes for `id` plus `4` bytes for the name length and then all the bytes corresponding to the `name` string plus the termination character. If the name has the empty string then only a length of 0 is sent. 

The underlying issue with using an Option is that there is no standard way to distinguish between a None or a Some on the wire (e.g. like the 0 length string does). Actual optional fields from a DDS perspective can be handled using the mechanisms described in [DDS-XTypes](https://www.omg.org/spec/DDS-XTypes/1.3/About-DDS-XTypes). We don't have yet easy support for such types on DustDDS.

Do you think the solution would be enough for your use case? If not and you would really need to have an option field the two options you have would be: 1) to make a custom implementation of the serde::Serialize and serde::Deserialize traits to decide how the option should be represented on the wire using the CDR standard representation; 2) Make a custom implementation of the DdsRepresentation trait of DustDDS and implement your own conversion to and from bytes to completely go around using the CDR standard representation.
