### ISSUE TITLE
Interoperability with FastDDS

### ISSUE THREAD

**Issue by samcarey** [s2e-systems/dust-dds#176]
I'm trying to test interoperability with FastDDS on Windows 11. You already test interop with CycloneDDS, right?

My test so far goes like this:
1. Download the [FastDDS Shapes Demo app](https://www.eprosima.com/index.php/products-all/eprosima-shapes-demo).
    - This requires filling out a form, but is pretty easy.
3. Run the contained `bin/ShapesDemo.exe`.
4. In the GUI, click "Publish" and accept the default settings to create a red square publisher.
5. Run the test programs below.

My Dust DDS test program is as follows, using version 0.4.0:
```rust
use dust_dds::{
    domain::domain_participant_factory::DomainParticipantFactory,
    infrastructure::{error::DdsResult, qos::QosKind},
};
use std::{thread, time::Duration};

fn main() -> DdsResult<()> {
    let participant = DomainParticipantFactory::get_instance().create_participant(
        0,
        QosKind::Default,
        None,
        &[],
    )?;
    loop {
        println!(
            "{:?}",
            participant
                .get_discovered_topics()?
                .into_iter()
                .map(|topic_handle| participant.get_discovered_topic_data(topic_handle).unwrap())
                .collect::<Vec<_>>()
        );
        thread::sleep(Duration::from_secs(1));
    }
}
```
The result is empty:
```console
[]
[]
...
```

For comparison, I tried the same thing using RustDDS:
```rust
use std::{thread, time::Duration};
use anyhow::Result;
use rustdds::DomainParticipant;

fn main() -> Result<()> {
    let participant = DomainParticipant::new(0)?;
    loop {
        println!("{:?}", participant.discovered_topics());
        thread::sleep(Duration::from_secs(1));
    }
}
```
and I get the following output:
```console
[]
[]
[]
[DiscoveredTopicData { updated_time: 2023-09-19T20:28:12.684058600Z, topic_data: TopicBuiltinTopicData { key: None, name: "Square", type_name: "ShapeType", durability: Some(Volatile), deadline: Some(Deadline(Duration { seconds: 2147483647, fraction: 4294967295 })), latency_budget: Some(LatencyBudget { duration: Duration { seconds: 0, fraction: 0 } }), liveliness: Some(Automatic { lease_duration: Duration { seconds: 2147483647, fraction: 4294967295 } }), reliability: Some(Reliable { max_blocking_time: Duration { seconds: 0, fraction: 429496730 } }), lifespan: Some(Lifespan { duration: Duration { seconds: 2147483647, fraction: 4294967295 } }), destination_order: Some(ByReceptionTimestamp), presentation: Some(Presentation { access_scope: Instance, coherent_access: false, ordered_access: false }), history: None, resource_limits: None, ownership: Some(Shared) } }]
...
```

So I'm wondering if there's an incompatibility or if I'm just using the Dust DDS API wrong?

**Comment by jrebelo** [comment]
We have looked into this and it looks indeed like a compatibility issue. We will investigate further and try to solve over the coming days.

**Comment by samcarey** [comment]
Thanks for doing that! Unfortunately, I'm still unsuccessful. 

I've set my version to the latest commit:
```toml
dust_dds = { git = "https://github.com/s2e-systems/dust-dds.git", rev = "e558f816c056d3043fe2a35b96f492327b80aa3a" }
```
Then I ran `cargo update`, `cargo clean`, and then reran the above programs back to back. I got the same results as before.
Have you tried running that code with the actual FastDDS ShapesDemo, or only the new interoperability tests?

**Comment by jrebelo** [comment]
A quick status update on this issue. We investigated a bit further and found the root cause for the behavior.

In DustDDS we are only using topic information publisher by a built-in Topics Announcer for find_topic(). However, neither CycloneDDS nor FastDDS send Topic information from a built-in Topics Announcer but instead use the topic information sent by the discovery of the readers and writers. This is understandable since there is a 1-to-1 relationship between a Reader/Writer and a Topic so it makes sense to include also these topics in the list of discovered topics. Our plan is to add this within the next week.

**Comment by jrebelo** [comment]
Hi @samcarey, took a little longer than we had foreseen but we have implemented a fix for this issue. I didn't have the chance to replicate your use case but I modified the test to find topics from FastDDS and that is working well. I hope this fixes the issue for your usage but if not, as usual don't hesitate in reopening this issue.
