### ISSUE TITLE
Why can't I receive it correctly using the example in the warehouse?

### ISSUE THREAD

**Issue by StellarGlyph** [s2e-systems/dust-dds#208]
I am a newbie. First I run `hello_world_subscriber.rs` in the example, and then I run `hello_world_publisher.rs`, but I cannot receive the response correctly.

**Comment by jrebelo** [comment]
Hi @StellarGlyph, I assume that you are running these tests on one computer so we can probably rule out problems with multicast. There are a couple of things you could try: 
1. Execute 'cargo test' to run the test cases and see if that is working. If not there are problem some issues with the system configuration that would need to be investigated further.
2. You could modify the hello world example to use a specific network card following this example: https://github.com/s2e-systems/dust-dds/blob/5b6120e6947179e2ed3ebaee889d09b81abf90c0/dds/examples/configuration.rs#L18C4-L18C4 The name of interface you should use depends on what is available on your machine.

Let us know about your results and we can see how to bring this forward.

**Comment by StellarGlyph** [comment]
Hello, thank you for replying to me. I am very happy. I am a newbie in DDS and I don’t know much about it. Here is what I did according to your instructions.

1. When I run the `cargo test` command, below is the list of test cases that failed
```rust
failures:
    deleted_readers_are_disposed_from_writer
    deleted_writers_are_disposed_from_reader
    participant_records_discovered_topics
    publisher_and_subscriber_regex_partition_is_matched
    publisher_regex_and_subscriber_partition_is_matched
    publisher_regex_and_subscriber_regex_partition_is_matched
    reader_discovers_disposed_writer_same_participant
    reader_discovers_writer_in_same_participant
    reader_matched_to_already_existing_writer_with_matched_reader
    two_participants_should_get_subscription_matched
    updated_readers_are_announced_to_writer
    updated_writers_are_announced_to_reader
    writer_discovers_reader_in_same_participant
    writer_matched_to_already_existing_reader_with_matched_writer
```
2. When I checked the network firewall, I found that the default incoming rule set by ufw was to deny. When I changed the rule to allow, the test case passed and it could run normally, but I understood that the incoming was coming from the external network. The network traffic is denied, but I don't understand why it affects the configuration of DDS. I understand that DDS is local. Can you enlighten me? Thanks!

**Comment by jrebelo** [comment]
Good to know that this solved the problems. DDS is quite an extensive standard which can take quite a bit of time to master. I would recommend going through the OMG standards and also some of the materials on the DDS foundation website https://www.dds-foundation.org/dds-resources/

For this particular case, it is good to know that DustDDS always uses messages transmitted over UDP for discovery and communication. This also happens locally, except that in this case the messages are transmitted over the local loopback so they probably never make their way out into the local network but they still get affected by firewall rules.
