### ISSUE TITLE
Scope of types supported for dds_gen

### ISSUE THREAD

**Issue by bhcsayx** [s2e-systems/dust-dds#214]
Hello, I am a newbie and recently I am trying to test interoperability functions with xtypes, and I am wondering what features of OMG IDL are implemented currently. Basically I tried to compile i11eperf IDL (https://github.com/eboasson/i11eperf/blob/master/idl/i11eperf.idl) and got errors as follows:

![image](https://github.com/s2e-systems/dust-dds/assets/43284805/c45ae5a6-208c-42fa-a184-b5e5b5dbbffa)
I tried to remove those annotators on structs, and got another error:

![image](https://github.com/s2e-systems/dust-dds/assets/43284805/995a502f-d023-4e1b-93e1-23b96da1e605)

I am wondering if these are expected or there are potential problems. Thanks in advance!

**Comment by bhcsayx** [comment]
Here is a small piece of code I wrote to invoke dds_gen:

`use dust_dds_gen::*;
use std::{fs::{File, self}, io::{Read, Write}, path::Path, env};

fn main() {
    let args: Vec<String> = env::args().collect();
    let mut file = File::open(args[1].as_str()).expect("Unable to open the file");
    let mut input = String::new();
    file.read_to_string(&mut input).expect("Unable to read the file");
    let compile_res = compile_idl(input.as_str());
    if let Ok(compiled_idl) = &compile_res {
        let mut compiled_idl_path = args[1].clone();
        compiled_idl_path = compiled_idl_path.replace("idl", "ridl");
        let mut file = File::create(compiled_idl_path).expect("Failed to create file");
        file.write_all(compiled_idl.as_bytes())
            .expect("Failed to write to file");
    }
    else if let Err(compile_err) = &compile_res {
        println!("Compile failed with error: {:?}", compile_err);
    }
}`

**Comment by jrebelo** [comment]
Hi @bhcsayx,

Thanks for reporting this issue. It is indeed the case that our IDL grammar didn't have support for annotations on the struct definitions. We have solved this on the referenced PR #215 so once that is merged you can use the latest version in the repo to generate the IDL you pointed to.
