### ISSUE TITLE
Cannot start a runtime from within a runtime

### ISSUE THREAD

**Issue by YeahhhhzZ** [s2e-systems/dust-dds#236]
dustdds not working in tokio main:
```rust
use common::dds_message::aos::transport::cyclone::DDSMessage;
use dust_dds::{
    domain::domain_participant_factory::DomainParticipantFactory,
    infrastructure::{listeners::NoOpListener, qos::QosKind, status::NO_STATUS},
};
#[tokio::main]
async fn main() {
    let domain_id = 0;
    let participant_factory = DomainParticipantFactory::get_instance();

    let participant = participant_factory
        .create_participant(domain_id, QosKind::Default, NoOpListener::new(), NO_STATUS)
        .unwrap();
}
```

**Comment by jrebelo** [comment]
To have Dust DDS working inside a Tokio main you have to make use of the async api functions. Here is a test which you can use as an example: https://github.com/s2e-systems/dust-dds/blob/007e3ed85055460f5d651420affe139b566a2602/dds/tests/tokio_runtime.rs#L28

I will add an actual example and a more clear note in the documentation about this.
