### ISSUE TITLE
DdsType derivation macro support for nested types

### ISSUE THREAD

**Issue by MattConradi** [s2e-systems/dust-dds#277]
Hello, I was wondering if there is any way/any plans to make it possible to apply the DdsType derivation macro to structs with nested types? 

The purpose of this is to create topic listeners and publishers that can handle XML messages with nested fields. Having used the IDL compiler on the IDLs for this specific XML standard, the generated structs are then non compileable as the DdsType derivation macro panics. 

Apologies for the lack of screenshots, but it would be against company policy

**Comment by jrebelo** [comment]
Hi @MattConradi,

We are indeed aware of this limitation and would like to add support for it but unfortunately I have no timeline for when it could be available. 

One alternative you could consider to allow you to progress is to manually implement the Type Support traits instead of using the derive. A good way to get started is to expand the output of the derive macro and then take it forward from there.

**Comment by MattConradi** [comment]
Ok I understand, thanks for answering so quickly! 
For expanding the output of the derive macro is there a specific approach/crate you'd recommend?

**Comment by jrebelo** [comment]
I think there will be more alternatives but I know of cargo-expand or if you use VS Code there is an option available to do that within the IDE: 
![image](https://github.com/s2e-systems/dust-dds/assets/2730147/c72a12ab-f063-49b2-ac02-2fe320e2a181)

With this being said, after a more thorough investigation we concluded that there is only a minor step needed to be able to support nested types. So we are preparing a PR to do that and that would likely solve the problem.

**Comment by jrebelo** [comment]
The PR adding support for nested types is now merged. Hopefully this solves your problem and you can just use the regular derive macro for your types. If it still doesn't work for some reason do not hesitate in re-opening the issue or creating a new one.

**Comment by MattConradi** [comment]
It works! Thank you so much, you're a life saver!

**Comment by jrebelo** [comment]
Thank you for confirming it works. Glad to know it helped!
